
export const testamentOptions = [
  {
    name: "旧约",
    books: [
      {
        cn: "圣经简介",
        cnAbbr: "简介",
        usfx: "_BIBLE_INTRO",
        en: "Bible Introduction",
        enAbbr: "B.Intr",
        esAbbr: "Int.B",
        chapters: 0,
        overviewOnly: true,
      },
      {
        cn: "旧约概论",
        cnAbbr: "旧概",
        usfx: "_OT_OVERVIEW",
        en: "Old Testament Overview",
        enAbbr: "OT.Intr",
        esAbbr: "AT.Intr",
        chapters: 0,
        overviewOnly: true,
      },
      { cn: "创世记", cnAbbr: "创", usfx: "GEN", chapters: 50 },
      { cn: "出埃及记", cnAbbr: "出", usfx: "EXO", chapters: 40 },
      { cn: "利未记", cnAbbr: "利", usfx: "LEV", chapters: 27 },
      { cn: "民数记", cnAbbr: "民", usfx: "NUM", chapters: 36 },
      { cn: "申命记", cnAbbr: "申", usfx: "DEU", chapters: 34 },
      { cn: "约书亚记", cnAbbr: "书", usfx: "JOS", chapters: 24 },
      { cn: "士师记", cnAbbr: "士", usfx: "JDG", chapters: 21 },
      { cn: "路得记", cnAbbr: "得", usfx: "RUT", chapters: 4 },
      { cn: "撒母耳记上", cnAbbr: "撒上", usfx: "1SA", chapters: 31 },
      { cn: "撒母耳记下", cnAbbr: "撒下", usfx: "2SA", chapters: 24 },
      { cn: "列王纪上", cnAbbr: "王上", usfx: "1KI", chapters: 22 },
      { cn: "列王纪下", cnAbbr: "王下", usfx: "2KI", chapters: 25 },
      { cn: "历代志上", cnAbbr: "代上", usfx: "1CH", chapters: 29 },
      { cn: "历代志下", cnAbbr: "代下", usfx: "2CH", chapters: 36 },
      { cn: "以斯拉记", cnAbbr: "拉", usfx: "EZR", chapters: 10 },
      { cn: "尼希米记", cnAbbr: "尼", usfx: "NEH", chapters: 13 },
      { cn: "以斯帖记", cnAbbr: "斯", usfx: "EST", chapters: 10 },
      { cn: "约伯记", cnAbbr: "伯", usfx: "JOB", chapters: 42 },
      { cn: "诗篇", cnAbbr: "诗", usfx: "PSA", chapters: 150 },
      { cn: "箴言", cnAbbr: "箴", usfx: "PRO", chapters: 31 },
      { cn: "传道书", cnAbbr: "传", usfx: "ECC", chapters: 12 },
      { cn: "雅歌", cnAbbr: "歌", usfx: "SNG", chapters: 8 },
      { cn: "以赛亚书", cnAbbr: "赛", usfx: "ISA", chapters: 66 },
      { cn: "耶利米书", cnAbbr: "耶", usfx: "JER", chapters: 52 },
      { cn: "耶利米哀歌", cnAbbr: "哀", usfx: "LAM", chapters: 5 },
      { cn: "以西结书", cnAbbr: "结", usfx: "EZK", chapters: 48 },
      { cn: "但以理书", cnAbbr: "但", usfx: "DAN", chapters: 12 },
      { cn: "何西阿书", cnAbbr: "何", usfx: "HOS", chapters: 14 },
      { cn: "约珥书", cnAbbr: "珥", usfx: "JOL", chapters: 3 },
      { cn: "阿摩司书", cnAbbr: "摩", usfx: "AMO", chapters: 9 },
      { cn: "俄巴底亚书", cnAbbr: "俄", usfx: "OBA", chapters: 1 },
      { cn: "约拿书", cnAbbr: "拿", usfx: "JON", chapters: 4 },
      { cn: "弥迦书", cnAbbr: "弥", usfx: "MIC", chapters: 7 },
      { cn: "那鸿书", cnAbbr: "鸿", usfx: "NAM", chapters: 3 },
      { cn: "哈巴谷书", cnAbbr: "哈", usfx: "HAB", chapters: 3 },
      { cn: "西番雅书", cnAbbr: "番", usfx: "ZEP", chapters: 3 },
      { cn: "哈该书", cnAbbr: "该", usfx: "HAG", chapters: 2 },
      { cn: "撒迦利亚书", cnAbbr: "亚", usfx: "ZEC", chapters: 14 },
      { cn: "玛拉基书", cnAbbr: "玛", usfx: "MAL", chapters: 4 },
    ],
  },
  {
    name: "新约",
    books: [
      {
        cn: "新约概论",
        cnAbbr: "新概",
        usfx: "_NT_OVERVIEW",
        en: "New Testament Overview",
        enAbbr: "NT.Intr",
        esAbbr: "NT.Intr",
        chapters: 0,
        overviewOnly: true,
      },
      { cn: "马太福音", cnAbbr: "太", usfx: "MAT", chapters: 28 },
      { cn: "马可福音", cnAbbr: "可", usfx: "MRK", chapters: 16 },
      { cn: "路加福音", cnAbbr: "路", usfx: "LUK", chapters: 24 },
      { cn: "约翰福音", cnAbbr: "约", usfx: "JHN", chapters: 21 },
      { cn: "使徒行传", cnAbbr: "徒", usfx: "ACT", chapters: 28 },
      { cn: "罗马书", cnAbbr: "罗", usfx: "ROM", chapters: 16 },
      { cn: "哥林多前书", cnAbbr: "林前", usfx: "1CO", chapters: 16 },
      { cn: "哥林多后书", cnAbbr: "林后", usfx: "2CO", chapters: 13 },
      { cn: "加拉太书", cnAbbr: "加", usfx: "GAL", chapters: 6 },
      { cn: "以弗所书", cnAbbr: "弗", usfx: "EPH", chapters: 6 },
      { cn: "腓立比书", cnAbbr: "腓", usfx: "PHP", chapters: 4 },
      { cn: "歌罗西书", cnAbbr: "西", usfx: "COL", chapters: 4 },
      { cn: "帖撒罗尼迦前书", cnAbbr: "帖前", usfx: "1TH", chapters: 5 },
      { cn: "帖撒罗尼迦后书", cnAbbr: "帖后", usfx: "2TH", chapters: 3 },
      { cn: "提摩太前书", cnAbbr: "提前", usfx: "1TI", chapters: 6 },
      { cn: "提摩太后书", cnAbbr: "提后", usfx: "2TI", chapters: 4 },
      { cn: "提多书", cnAbbr: "多", usfx: "TIT", chapters: 3 },
      { cn: "腓利门书", cnAbbr: "门", usfx: "PHM", chapters: 1 },
      { cn: "希伯来书", cnAbbr: "来", usfx: "HEB", chapters: 13 },
      { cn: "雅各书", cnAbbr: "雅", usfx: "JAS", chapters: 5 },
      { cn: "彼得前书", cnAbbr: "彼前", usfx: "1PE", chapters: 5 },
      { cn: "彼得后书", cnAbbr: "彼后", usfx: "2PE", chapters: 3 },
      { cn: "约翰一书", cnAbbr: "约一", usfx: "1JN", chapters: 5 },
      { cn: "约翰二书", cnAbbr: "约二", usfx: "2JN", chapters: 1 },
      { cn: "约翰三书", cnAbbr: "约三", usfx: "3JN", chapters: 1 },
      { cn: "犹大书", cnAbbr: "犹", usfx: "JUD", chapters: 1 },
      { cn: "启示录", cnAbbr: "启", usfx: "REV", chapters: 22 },
    ],
  },
];
