
export const testamentOptions = [
  {
    name: "旧约",
    books: [
      {
        cn: "旧约概论",
        usfx: "_OT_OVERVIEW",
        en: "Old Testament Overview",
        chapters: 0,
        overviewOnly: true,
      },
      { cn: "创世记", usfx: "GEN", chapters: 50 },
      { cn: "出埃及记", usfx: "EXO", chapters: 40 },
      { cn: "利未记", usfx: "LEV", chapters: 27 },
      { cn: "民数记", usfx: "NUM", chapters: 36 },
      { cn: "申命记", usfx: "DEU", chapters: 34 },
      { cn: "约书亚记", usfx: "JOS", chapters: 24 },
      { cn: "士师记", usfx: "JDG", chapters: 21 },
      { cn: "路得记", usfx: "RUT", chapters: 4 },
      { cn: "撒母耳记上", usfx: "1SA", chapters: 31 },
      { cn: "撒母耳记下", usfx: "2SA", chapters: 24 },
      { cn: "列王纪上", usfx: "1KI", chapters: 22 },
      { cn: "列王纪下", usfx: "2KI", chapters: 25 },
      { cn: "历代志上", usfx: "1CH", chapters: 29 },
      { cn: "历代志下", usfx: "2CH", chapters: 36 },
      { cn: "以斯拉记", usfx: "EZR", chapters: 10 },
      { cn: "尼希米记", usfx: "NEH", chapters: 13 },
      { cn: "以斯帖记", usfx: "EST", chapters: 10 },
      { cn: "约伯记", usfx: "JOB", chapters: 42 },
      { cn: "诗篇", usfx: "PSA", chapters: 150 },
      { cn: "箴言", usfx: "PRO", chapters: 31 },
      { cn: "传道书", usfx: "ECC", chapters: 12 },
      { cn: "雅歌", usfx: "SNG", chapters: 8 },
      { cn: "以赛亚书", usfx: "ISA", chapters: 66 },
      { cn: "耶利米书", usfx: "JER", chapters: 52 },
      { cn: "耶利米哀歌", usfx: "LAM", chapters: 5 },
      { cn: "以西结书", usfx: "EZK", chapters: 48 },
      { cn: "但以理书", usfx: "DAN", chapters: 12 },
      { cn: "何西阿书", usfx: "HOS", chapters: 14 },
      { cn: "约珥书", usfx: "JOL", chapters: 3 },
      { cn: "阿摩司书", usfx: "AMO", chapters: 9 },
      { cn: "俄巴底亚书", usfx: "OBA", chapters: 1 },
      { cn: "约拿书", usfx: "JON", chapters: 4 },
      { cn: "弥迦书", usfx: "MIC", chapters: 7 },
      { cn: "那鸿书", usfx: "NAM", chapters: 3 },
      { cn: "哈巴谷书", usfx: "HAB", chapters: 3 },
      { cn: "西番雅书", usfx: "ZEP", chapters: 3 },
      { cn: "哈该书", usfx: "HAG", chapters: 2 },
      { cn: "撒迦利亚书", usfx: "ZEC", chapters: 14 },
      { cn: "玛拉基书", usfx: "MAL", chapters: 4 }
    ]
  },
  {
    name: "新约",
    books: [
      {
        cn: "新约概论",
        usfx: "_NT_OVERVIEW",
        en: "New Testament Overview",
        chapters: 0,
        overviewOnly: true,
      },
      { cn: "马太福音", usfx: "MAT", chapters: 28 },
      { cn: "马可福音", usfx: "MRK", chapters: 16 },
      { cn: "路加福音", usfx: "LUK", chapters: 24 },
      { cn: "约翰福音", usfx: "JHN", chapters: 21 },
      { cn: "使徒行传", usfx: "ACT", chapters: 28 },
      { cn: "罗马书", usfx: "ROM", chapters: 16 },
      { cn: "哥林多前书", usfx: "1CO", chapters: 16 },
      { cn: "哥林多后书", usfx: "2CO", chapters: 13 },
      { cn: "加拉太书", usfx: "GAL", chapters: 6 },
      { cn: "以弗所书", usfx: "EPH", chapters: 6 },
      { cn: "腓立比书", usfx: "PHP", chapters: 4 },
      { cn: "歌罗西书", usfx: "COL", chapters: 4 },
      { cn: "帖撒罗尼迦前书", usfx: "1TH", chapters: 5 },
      { cn: "帖撒罗尼迦后书", usfx: "2TH", chapters: 3 },
      { cn: "提摩太前书", usfx: "1TI", chapters: 6 },
      { cn: "提摩太后书", usfx: "2TI", chapters: 4 },
      { cn: "提多书", usfx: "TIT", chapters: 3 },
      { cn: "腓利门书", usfx: "PHM", chapters: 1 },
      { cn: "希伯来书", usfx: "HEB", chapters: 13 },
      { cn: "雅各书", usfx: "JAS", chapters: 5 },
      { cn: "彼得前书", usfx: "1PE", chapters: 5 },
      { cn: "彼得后书", usfx: "2PE", chapters: 3 },
      { cn: "约翰一书", usfx: "1JN", chapters: 5 },
      { cn: "约翰二书", usfx: "2JN", chapters: 1 },
      { cn: "约翰三书", usfx: "3JN", chapters: 1 },
      { cn: "犹大书", usfx: "JUD", chapters: 1 },
      { cn: "启示录", usfx: "REV", chapters: 22 }
    ]
  }
];
